apiVersion: v1
kind: Service
metadata:
  labels:
    app: mobile
  name: mobile-api
spec:
  ports:
    - name: 80-5000
      port: 80
      protocol: TCP
      targetPort: 5000
    - name: 2222-22
      port: 2222
      protocol: TCP
      targetPort: 22
    - name: 12345-12345
      port: 12345
      protocol: TCP
      targetPort: 12345
  selector:
    app: mobile
    run: api
    status: live
  type: NodePort
